name: CI
on:
  push:
  workflow_dispatch:
  repository_dispatch:
    types: changeme
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use wasmtime 0.21.0
      uses: mwilliamson/setup-wasmtime-action@v1
      with:
        wasmtime-version: "0.21.0"
    - name: rust
      run: |
        rustup target add wasm32-wasi
        rustc hello.rs --target wasm32-wasi
        wasmtime hello.wasm
    - name: as
      run: |
        npm run build
        npm run wasmtime