name: CI
on:
  push:
  workflow_dispatch:
  repository_dispatch:
    types: changeme
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use wasmtime 0.21.0
      uses: mwilliamson/setup-wasmtime-action@v1
      with:
        wasmtime-version: "0.21.0"
    - name: test
      run: |
        wasmtime --version
